---
- name: Run miners
  docker_container:
      image: "ryeguy/wolf9466-cpuminer-multi:latest"
      name: "miner_{{ item.username }}"
      recreate: "{{ 'yes' if configs.changed else 'no' }}"
      log_driver: gelf
      log_options:
          gelf-address: udp://localhost:12201
          tag: "miner_{{ item.username }}"
      command: "run_minerd.sh -a cryptonight -o stratum+tcp://xmr.pool.minergate.com:45560 -u {{ item.email }} -p x -t {{ item.threads }}"
  with_items: "{{ monero_users }}"
