---
- name: Create miner directory
  file:
      path: "/opt/data/monero-miner"
      state: directory

- name: Copy templates
  template:
      src: "{{ item }}.j2"
      dest: "/opt/data/monero-miner/{{ item }}"
  with_items:
      - Dockerfile
      - moneroCPU.sh
      - CPU-bind.sh

- name: Check scripts
  file:
      path: "/opt/data/monero-miner/{{ item }}"
      mode: 0111
  with_items:
      - moneroCPU.sh
      - CPU-bind.sh

- name: Build image
  docker_image:
      name: monero_miner
      path: "/opt/data/monero-miner"

- name: Run dockers
  docker_container:
      image: monero_miner
      name: "miner_{{ item.username }}"
      recreate: yes
      env:
          USERNAME: "{{ item.email }}"
          THREADS: "{{ item.threads }}"
  with_items: "{{ monero_users }}"

- name: Run CPU-bind
  shell: /opt/data/monero-miner/CPU-bind.sh

- name: Delete files
  file:
      path: "/opt/data/monero-miner"
      state: absent
