---
- name: Create logstash dir
  file:
      path: "/opt/data/logstash/configs"
      state: directory

- name: Copy logstash dockerfile
  template:
      src: "Dockerfile.j2"
      dest: "/opt/data/logstash/Dockerfile"
  register: dockerfile

- name: Copy logstash configs
  template:
      src: "{{ item }}.j2"
      dest: "/opt/data/logstash/configs/{{ item }}"
  with_items:
      - pipeline.conf
  register: config

- name: Create logstash image
  docker_image:
      force: "{{ 'yes' if dockerfile.changed else 'no' }}"
      path: "/opt/data/logstash"
      name: "logstash"
  register: image

- name: Start logstash container
  docker_container:
      name: logstash
      image: logstash
      recreate: "{{ 'yes' if image.changed or config.changed else 'no' }}"
      command: "logstash -f /logstash.conf"
      ports:
          - "12201:12201/udp"
      links:
          - influxdb
      volumes:
          - /opt/data/logstash/configs/pipeline.conf:/logstash.conf:ro
          - /var/run/docker.sock:/var/run/docker.sock:ro

