---
- name: Create logstash dir
  file:
      path: "/opt/data/logstash/configs"
      state: directory

- name: Copy logstash dockerfile
  template:
      src: "Dockerfile.j2"
      dest: "/opt/data/logstash/Dockerfile"

- name: Copy logstash configs
  template:
      src: "{{ item }}.j2"
      dest: "/opt/data/logstash/configs/{{ item }}"
  with_items:
      - logstash.yml
      - pipeline.conf

- name: Create logstash image
  docker_image:
      path: "/opt/data/logstash"
      name: "logstash"
  register: image

- name: Start logstash container
  docker_container:
      name: logstash
      image: logstash
      recreate: "{{ 'yes' if image.changed else 'no' }}"
      links:
          - influxdb
      volumes:
          - /opt/data/logstash/configs/pipeline.conf:/usr/share/logstash/pipeline/logstash.conf:ro
          - /opt/data/logstash/configs/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
          - /var/run/docker.sock:/var/run/docker.sock:ro

