---
- name: Start influxdb container
  docker_container:
      name: influxdb
      image: influxdb:1.2.4
      env:
          INFLUXDB_DATA_QUERY_LOG_ENABLED: "false"
          INFLUXDB_HTTP_AUTH_ENABLED: "true"
      volumes:
          - "/opt/data/influxdb:/var/lib/influxdb"
      expose:
          - 8086
          - 8083
