---
- name: Start influxdb container
  docker_container:
      name: influxdb
      image: influxdb:1.3.7
      recreate: yes
      env:
          INFLUXDB_DATA_QUERY_LOG_ENABLED: false
          INFLUXDB_HTTP_AUTH_ENABLED: true
      volumes:
          - "/opt/data/influxdb:/var/lib/influxdb"
      ports:
          - 127.0.0.1:8086:8086

- name: Wait for up
  command: sleep 20

- name: Create user
  uri:
    url: http://127.0.0.1:8086/query
    method: POST
    user: "{{ influxdb_user }}"
    password: "{{ influxdb_password }}"
    body: "{{ item }}"
#  no_log: True
  with_items:
    - "q=CREATE USER {{ influxdb_user }} WITH PASSWORD '{{ influxdb_password }}' WITH ALL PRIVILEGES"
    - "q=CREATE DATABASE \"{{ influxdb_db }}\" WITH DURATION 14d NAME \"two_weeks\""
