---
- name: Create grafana dir
  file:
      path: /opt/data/grafana/config
      state: directory

- name: Copy grafana configs
  template:
      src: "grafana.ini.j2"
      dest: "/opt/data/grafana/config/grafana.ini"

- include_tasks: candlestick_plugin.yml
  when:
    - update_candlesticks is defined
    - update_candlesticks

- name: Start grafana container
  docker_container:
    image: "grafana/grafana:{{ grafana_version }}"
    name: grafana
    recreate: "{{ 'yes' if force_update | default(False) else 'no' }}"
    restart_policy: always
    env:
        VIRTUAL_HOST: monitoring.cuttlerat.ru
        VIRTUAL_PORT: 3000
        LETSENCRYPT_HOST: monitoring.cuttlerat.ru
        LETSENCRYPT_EMAIL: avkioller@gmail.com
        GF_SERVER_ROOT_URL: https://monitoring.cuttlerat.ru
    volumes:
        - /opt/data/grafana:/var/lib/grafana
        - /opt/data/grafana/config/grafana.ini:/etc/grafana/grafana.ini
    links:
        - influxdb

