---
- name: Copy builder script
  copy:
      src: "files/builder.sh"
      dest: "/opt/data/pybot/builder.sh"
      mode: 0700

- name: Install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - inotify-tools
    - daemon

#TODO make it idempotent
- name: Run builder
  command: bash -c "daemon -- /opt/data/pybot/builder.sh &>/var/log/builder.log"
