---
- name: Ensure webdav directory is exists
  file:
    path: "{{ base_dir }}/webdav"
    state: directory

- name: Create webdav container
  docker_container:
    name: webdav
    image: "idelsink/webdav:{{ webdav_version }}"
    volumes:
      - "{{ base_dir }}/webdav:/webdav"
    env:
      VIRTUAL_HOST: webdav.hotkosc.ru
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: webdav.hotkosc.ru
      LETSENCRYPT_EMAIL: hotkosc@gmail.com
      USERNAME: "{{ webdav_username }}"
      PASSWORD: "{{ webdav_password }}"
