---
- name: Ensure directory is exists
  file:
    path: "/opt/data/prosody/config"
    state: directory
    
- name: Copy config
  template:
    src: prosody.cfg.lua.j2
    dest: "/opt/data/prosody/config/prosody.cfg.lua"

- name: Ensure database is exists
  file:
    path: "/opt/data/prosody/config/prosody.sqlite"
    state: touch
    owner: 102
    group: 106

- name: Start container
  docker_container:
    image: prosody/prosody:0.9
    name: prosody
    recreate: yes
    restart_policy: always
    ports:
      - 5222:5222
      - 5269:5269 
    env:
      VIRTUAL_HOST: hotkosc.ru
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: hotkosc.ru
      LETSENCRYPT_EMAIL: avkioller@gmail.com
      DOMAIN: hotkosc.ru 
      PASSWORD: "{{ jabber_password }}"
    volumes:
      - "/opt/data/prosody/config/prosody.cfg.lua:/etc/prosody/prosody.cfg.lua"
      - "/opt/data/prosody/config/prosody.sqlite:/var/lib/prosody/prosody.sqlite"
    #  - "/logs/prosody:/var/log/prosody"
    #  - "/data/prosody/modules:/usr/lib/prosody-modules"
