FROM logstash:5.6.5

RUN logstash-plugin install logstash-output-influxdb
RUN logstash-plugin install logstash-input-http_poller

ENV TZ=Europe/Moscow
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
