---
- name: Start nginx-proxy
  docker_container:
      image: "jrcs/letsencrypt-nginx-proxy-companion"
      name: letsencrypt-nginx-proxy
      recreate: no
      restart_policy: always
      volumes:
          - /etc/nginx/certs:/etc/nginx/certs
          - /var/run/docker.sock:/var/run/docker.sock:ro
      volumes_from:
          - nginx-proxy
